### ISSUE TITLE
Modify base.html and a base.css file in a static folder.

### ISSUE THREAD

**Issue by utkarsh23** [TaskForceNITKS/NITK-SC-Portal#1]
All our html pages will extend base.html, so add the following into this page:
* CDNs for materialize framework
* Materialize header - should be fixed at the top on scrolling down
* Materialize footer

No design scheme has been decided upon yet, so just keep the materialize default styling and make the base.css file as small as possible.

**Comment by shivampotdar** [comment]
Shall we add materialize files to local folders, since this website is going to be internal to NITK also?
